export enum BlockResource {
  air = 0,
  stone,
  grass_block,
  dirt,
  cobblestone,
  planks,
  sapling,
  bedrock,
  water_flowing,
  water,
  lava_flowing,
  lava,
  sand,
  gravel,
  gold_ore,
  iron_ore,
  coal_ore,
  log,
  leaves,
  glass = 20,
  lapis_ore,
  lapis_block,
  sandstone = 24,
  bed = 26,
  cobweb = 30,
  bush,
  wool = 35,
  dandelion = 37,
  blue_rose,
  brown_mushroom,
  red_mushroom,
  gold_block,
  iron_block,
  double_slab,
  slab,
  bricks,
  tnt,
  bookshelf,
  mossy_cobblestone,
  obsidian,
  torch,
  fire,
  wooden_stairs = 53,
  chest,
  diamond_ore = 56,
  diamond_block,
  crafting_table,
  wheat,
  farmland,
  furnace,
  lit_furnace,
  sign,
  wooden_door,
  ladder,
  cobblestone_stairs = 67,
  wall_sign,
  iron_door = 71,
  redstone_ore = 73,
  lit_redstone_ore,
  snow = 78,
  ice,
  snow_block,
  cactus,
  clay,
  sugarcane,
  fence = 85,
  netherrack = 87,
  glowstone = 89,
  bedrock_invisible = 95,
  trapdoor,
  stone_bricks = 98,
  glass_pane = 102,
  melon,
  melon_stem = 105,
  fence_gate = 107,
  brick_stairs,
  stone_brick_stairs,
  nether_bricks = 112,
  nether_brick_stairs = 114,
  sandstone_stairs = 128,
  quartz_block = 155,
  quartz_stairs,
  stonecutter = 245,
  lit_obsidian,
  nether_reactor_core,
  update,
  ateupd,
  grass_block_carried = 253,
  leaves_carried,
  stone_1
}