export enum BiomeResource {
  ocean = 0,
  plains,
  desert,
  extreme_hills,
  forest,
  taiga,
  swampland,
  river,
  hell,
  sky,
  legacy_frozen_ocean,
  frozen_river,
  ice_flats,
  ice_mountains,
  mushroom_island,
  mushroom_island_shore,
  beaches,
  desert_hills,
  forest_hills,
  taiga_hills,
  smaller_extreme_hills,
  jungle,
  jungle_hills,
  jungle_edge,
  deep_ocean,
  stone_beach,
  cold_beach,
  birch_forest,
  birch_forest_hills,
  roofed_forest,
  taiga_cold,
  taiga_cold_hills,
  redwood_taiga,
  redwood_taiga_hills,
  extreme_hills_with_trees,
  savanna,
  savanna_rock,
  mesa,
  mesa_rock,
  mesa_clear_rock,
  warm_ocean,
  deep_warm_ocean,
  lukewarm_ocean,
  deep_lukewarm_ocean,
  cold_ocean,
  deep_cold_ocean,
  frozen_ocean,
  deep_frozen_ocean,
  sky_island_low,
  sky_island_medium,
  sky_island_high,
  sky_island_barren,
  void = 127,
  mutated_plains = 129,
  mutated_desert,
  mutated_extreme_hills,
  mutated_forest,
  mutated_taiga,
  mutated_swampland,
  mutated_ice_flats = 140,
  mutated_jungle = 149,
  mutated_jungle_edge = 151,
  mutated_birch_forest = 155,
  mutated_birch_forest_hills,
  mutated_roofed_forest,
  mutated_taiga_cold,
  mutated_redwood_taiga = 160,
  mutated_redwood_taiga_hills,
  mutated_extreme_hills_with_trees,
  mutated_savanna,
  mutated_savanna_rock,
  mutated_mesa,
  mutated_mesa_rock,
  mutated_mesa_clear_rock,
  bamboo_jungle,
  bamboo_jungle_hills
}