export enum BiomeResource {
  ocean = 0,
  plains,
  desert,
  extreme_hills,
  forest,
  taiga,
  swampland,
  river,
  hell,
  the_end,
  legacy_frozen_ocean,
  frozen_river,
  ice_plains,
  ice_mountains,
  mushroom_island,
  mushroom_island_shore,
  beach,
  desert_hills,
  forest_hills,
  taiga_hills,
  extreme_hills_edge,
  jungle,
  jungle_hills,
  jungle_edge,
  deep_ocean,
  stone_beach,
  cold_beach,
  birch_forest,
  birch_forest_hills,
  roofed_forest,
  cold_taiga,
  cold_taiga_hills,
  mega_taiga,
  mega_taiga_hills,
  extreme_hills_plus_trees,
  savanna,
  savanna_plateau,
  mesa,
  mesa_plateau_stone,
  mesa_plateau,
  warm_ocean,
  deep_warm_ocean,
  lukewarm_ocean,
  deep_lukewarm_ocean,
  cold_ocean,
  deep_cold_ocean,
  frozen_ocean,
  deep_frozen_ocean,
  small_end_islands,
  end_midlands,
  end_highlands,
  end_barrens,
  the_void = 127,
  sunflower_plains = 129,
  desert_mutated,
  extreme_hills_mutated,
  flower_forest,
  taiga_mutated,
  swampland_mutated,
  ice_plains_spikes = 140,
  jungle_mutated = 149,
  jungle_edge_mutated = 151,
  birch_forest_mutated = 155,
  birch_forest_hills_mutated,
  roofed_forest_mutated,
  cold_taiga_mutated,
  mega_spruce_taiga = 160,
  redwood_taiga_hills_mutated,
  extreme_hills_plus_trees_mutated,
  savanna_mutated,
  savanna_plateau_mutated,
  mesa_bryce,
  mesa_plateau_stone_mutated,
  mesa_plateau_mutated,
  bamboo_jungle = 168,
  bamboo_jungle_hills
}