export type EffectResource = typeof EffectResource[keyof typeof EffectResource];

export const EffectResource = {
  protection: 0,
  fire_protection: 1,
  feather_falling: 2,
  blast_protection: 3,
  projectile_protection: 4,
  respiration: 5,
  aqua_affinity: 6,
  thorns: 7,
  depth_strider: 8,
  frost_walker: 9,
  binding_curse: 10,
  sharpness: 16,
  smite: 17,
  bane_of_arthropods: 18,
  knockback: 19,
  fire_aspect: 20,
  looting: 21,
  efficiency: 32,
  silk_touch: 33,
  unbreaking: 34,
  fortune: 35,
  power: 48,
  punch: 49,
  flame: 50,
  infinity: 51,
  luck_of_the_sea: 61,
  lure: 62,
  loyalty: 65,
  impaling: 66,
  riptide: 67,
  channeling: 68,
  mending: 70,
  vanishing_curse: 71
} as const;